// Tokens del diseño de Stitch, tal cual (colores, radios, espaciados, tipografías).
// Se compila UNA vez a css/tailwind.css (ver package.json: `npm run build:css`) y
// ese archivo se commitea -- el sitio en producción sigue siendo HTML estático
// sin build ni CDN de Tailwind en runtime.
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html'],
  theme: {
    extend: {
      colors: {
        primary: '#9ee939',
        'surface-container-highest': '#323631',
        background: '#101410',
        'inverse-primary': '#416900',
        'on-secondary-fixed': '#121f00',
        'on-primary': '#1f3700',
        'on-tertiary-fixed-variant': '#005321',
        'primary-container': '#84cc16',
        'tertiary-fixed': '#6bff8f',
        surface: '#101410',
        'surface-tint': '#91db2a',
        'tertiary-container': '#37d269',
        outline: '#8b947d',
        'on-tertiary': '#003915',
        'surface-container-high': '#272b26',
        'on-tertiary-container': '#005523',
        'on-tertiary-fixed': '#002109',
        'tertiary-fixed-dim': '#4ae176',
        'outline-variant': '#424936',
        error: '#ffb4ab',
        'primary-fixed-dim': '#91db2a',
        'on-primary-container': '#315200',
        'surface-container-low': '#191d18',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#304f00',
        'primary-fixed': '#acf847',
        'on-secondary': '#213600',
        'inverse-surface': '#e0e4dc',
        'surface-container-lowest': '#0b0f0b',
        'on-surface-variant': '#c1cab0',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#2d312d',
        'surface-bright': '#363a35',
        'on-background': '#e0e4dc',
        'surface-dim': '#101410',
        'on-secondary-fixed-variant': '#334f00',
        tertiary: '#5aef82',
        'secondary-container': '#83c300',
        'secondary-fixed-dim': '#98da27',
        secondary: '#9ddf2e',
        'on-secondary-container': '#304b00',
        'surface-variant': '#323631',
        'secondary-fixed': '#b2f746',
        'on-surface': '#e0e4dc',
        'surface-container': '#1d211c',
        'on-primary-fixed': '#102000',
        'error-container': '#93000a',
      },
      borderRadius: { DEFAULT: '1rem', lg: '2rem', xl: '3rem', full: '9999px' },
      spacing: {
        margin: '1.25rem',
        'space-2xl': '4rem',
        'margin-desktop': '2.5rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        gutter: '1.25rem',
        'space-xs': '0.25rem',
        'gutter-desktop': '2rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'label-pill': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'display-hero': ['Space Grotesk', 'sans-serif'],
        'display-hero-mobile': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-pill': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.14em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '700' }],
        'display-hero': ['56px', { lineHeight: '60px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-hero-mobile': ['38px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '46px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
}
